version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

  deploy_staging:
    machine:
      enabled: true

    working_directory: ~/client

    steps:
      - add_ssh_keys:
          fingerprints:
            - "e8:0f:9a:ac:5a:33:13:cc:fc:b0:a4:73:56:23:da:b7"
      - checkout
      - run:
          name: Push Master to Staging
          command: |
            git push https://github.com/tylercaceres/c1.git master:staging

  deploy_production:
    machine:
      enabled: true

    working_directory: ~/client

    steps:
      - add_ssh_keys:
          fingerprints:
            - "e8:0f:9a:ac:5a:33:13:cc:fc:b0:a4:73:56:23:da:b7"
      - checkout
      - run:
          name: Push Staging to Production
          command: |
            git push https://github.com/tylercaceres/c1.git staging:production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - staging
              # ignore: production
      - deploy_staging:
          filters:
            branches:
              only: master
            #  ignore: production
          requires:
            - build

      - deploy_production:
          filters:
            branches:
              only: staging
            #  ignore: production
          requires:
            - build
