name: CI

on:
  push:
    branches:
    - master

jobs:
  test:
    name: run test
    runs-on: ubuntu-latest
    steps:
      - name: wait wurt
        run: |
          echo so sad...
          echo hello, world
          npm test
          
          
