name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      # - name: npm install, npm lint, npm test, npm build
      #   run: |
      #     npm install
      #     npm test
      - name: new branch
        run: git push https://github.com/tylercaceres/c1.git master:production
